//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenVanHuong_BTTL_141124.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Diem
    {
        [Key, Column(Order = 0)]
        public int maSV { get; set; }
        [Key, Column(Order = 1)]
        public int maMonHoc { get; set; }
        [Range(0, 10)]
        [Display(Name ="Điểm TB")]
        public Nullable<decimal> diemTBM { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
