//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenVanHuong_BTTL_141124.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.Diems = new HashSet<Diem>();
        }
        [Key]
        [Display(Name ="Mã SV")]
        public int maSV { get; set; }
        [Display(Name ="Họ tên")]
        public string hoTen { get; set; }
        [Display(Name = "Ngày sinh")]
        public Nullable<System.DateTime> ngaySinh { get; set; }
        [Display(Name = "Giới tính")]
        public Nullable<bool> gioiTinh { get; set; }
        public Nullable<int> maLop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Điểm")]
        public virtual ICollection<Diem> Diems { get; set; }
        [Display(Name = "Lớp")]
        public virtual Lop Lop { get; set; }
    }
}
