//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _26_LTUDDND_NguyenVanHuong_21103100115_DHTI15A5HN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.CompilerServices;

    public partial class HoaDon
    {
        [Key, Column(Order = 0)]
        public int SoHD { get; set; }
        [Key, Column(Order = 1)]
        public int MaMon { get; set; }
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        [Range(1, 50)]
        public Nullable<int> SoLuong { get; set; }
    
        public virtual MonAn MonAn { get; set; }
    }
}
