//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _26_LTUDDND_NguyenVanHuong_21103100115_DHTI15A5HN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
        [Key]
        [Required]
        public int MaMon { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 5)]
        public string TenMon { get; set; }
        [Required]
        public string LoaiMon { get; set; }
        [Required]
        
        [Range(1, maximum:99999999999)]
        public Nullable<decimal> Gia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
